import { chromium } from "playwright";
import { db } from "../tg-session";
import { shot, go, probe, CLICKABLES } from "./lib";
const PASS = "Zz2Test2026!";
(async () => {
  const browser = await chromium.launch({ headless: true });
  const ctx = await browser.newContext({ viewport: { width: 360, height: 640 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  await ctx.addInitScript(`try{localStorage.setItem("wesetup.last-seen-build-sha","zzz")}catch(e){};document.addEventListener('DOMContentLoaded',function(){var s=document.createElement('style');s.textContent='nextjs-portal{display:none!important}';document.head.appendChild(s)})`);
  const page = await ctx.newPage();
  const errs: string[] = [];
  page.on("response", (r) => { if (r.status() >= 400 && !/_next\/static|favicon/.test(r.url())) errs.push(`http ${r.status()} ${r.request().method()} ${r.url().slice(-70)}`); });
  await go(page, "http://localhost:3021/mini/login", 6000);
  await page.locator("input[name=phone]").click();
  await page.keyboard.type("+7 921 000 77 88", { delay: 30 });
  console.log("phone field =", JSON.stringify(await page.locator("input[name=phone]").inputValue()));
  await page.locator("input[name=password]").fill(PASS);
  await page.getByRole("button", { name: "Войти" }).click();
  await page.waitForTimeout(9000);
  console.log("URL", page.url());
  await shot(page, "10-newstaff-home", true);
  console.log("HOME", (await page.evaluate(`document.body.innerText.slice(0,2000)`)));
  await go(page, "http://localhost:3021/mini/sections", 4000);
  await shot(page, "10-newstaff-sections", true);
  console.log("SECTIONS", JSON.stringify(await page.evaluate(CLICKABLES), null, 1).slice(0,3000));
  await go(page, "http://localhost:3021/journals", 5000);
  await shot(page, "10-newstaff-journals", true);
  console.log("JOURNALS", (await page.evaluate(`document.body.innerText.slice(0,1500)`)));
  console.log("ERRS", JSON.stringify(errs, null, 1));
  await browser.close();
  await db.$disconnect();
})();
