import { chromium } from "playwright";
import { db } from "../tg-session";
import { shot, go, CLICKABLES } from "./lib";
const PASS = "Zz2Test2026!";
(async () => {
  const browser = await chromium.launch({ headless: true });
  const ctx = await browser.newContext({ viewport: { width: 360, height: 640 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  await ctx.addInitScript(`try{localStorage.setItem("wesetup.last-seen-build-sha","zzz")}catch(e){}`);
  const page = await ctx.newPage();
  const errs: string[] = [];
  page.on("response", (r) => { if (r.status() >= 400 && !/_next\/static|favicon/.test(r.url())) errs.push(`http ${r.status()} ${r.request().method()} ${r.url().slice(-70)}`); });
  await go(page, "http://localhost:3021/mini/login", 6000);
  await page.locator("input[name=phone]").click();
  await page.keyboard.type("+79210007788", { delay: 20 });
  await page.locator("input[name=password]").fill(PASS);
  await page.getByRole("button", { name: "Войти" }).click();
  await page.waitForTimeout(8000);
  console.log("URL", page.url());
  await shot(page, "16-zz2-today", true);
  console.log("TODAY", (await page.evaluate(`document.body.innerText.slice(0,1200)`)));
  await go(page, "http://localhost:3021/mini/sections", 4000);
  console.log("SECTIONS", JSON.stringify((await page.evaluate(CLICKABLES) as string[]).filter(x=>x.includes("->/")), null, 1));
  await go(page, "http://localhost:3021/journals", 5000);
  await shot(page, "16-zz2-journals", true);
  console.log("JOURNALS-URL", page.url());
  console.log("JOURNALS", (await page.evaluate(`document.body.innerText.slice(0,1200)`)));
  await go(page, "http://localhost:3021/journals/hygiene", 5000);
  await shot(page, "16-zz2-hygiene", true);
  console.log("HYG-URL", page.url());
  console.log("HYG", (await page.evaluate(`document.body.innerText.slice(0,1200)`)));
  console.log("ERRS", JSON.stringify(errs, null, 1));
  await browser.close(); await db.$disconnect();
})();
