import { openTelegramSession, db } from "../tg-session";
import { shot, go, probe, CLICKABLES } from "./lib";
(async () => {
  const s = await openTelegramSession({ role: "ownerA", width: 360, height: 640, theme: "light" });
  const page = s.page;
  await go(page, s.base + "/settings/equipment", 7000);
  await page.getByRole("button", { name: "Добавить оборудование" }).click();
  await page.waitForTimeout(1500);
  const sels = page.locator("select");
  await page.locator("input").first().fill("ZZ2 Холодильник тест");
  await sels.nth(0).selectOption({ label: "Холодильник" });
  await sels.nth(1).selectOption({ label: "Горячий цех" });
  const ins = page.locator("input");
  const n = await ins.count(); console.log("inputs", n);
  for (let i = 0; i < n; i++) console.log(i, await ins.nth(i).getAttribute("placeholder"));
  await page.locator("input[placeholder*='например 2']").fill("1");
  await page.locator("input[placeholder*='например 6']").fill("5");
  await shot(page, "20-filled");
  const wait = page.waitForResponse((r:any)=>r.request().method()==="POST"&&r.url().includes("/api"), { timeout: 120000 }).catch(()=>null);
  await page.getByRole("button", { name: "Создать" }).click();
  const rr = await wait; if (rr) console.log("CREATE", rr.status(), rr.url().slice(-50), (await rr.text().catch(()=> "")).slice(0,200));
  await page.waitForTimeout(3500);
  await shot(page, "20-after-create", true);
  console.log("LIST", (await page.evaluate(`document.body.innerText.slice(0,1400)`)));
  const eq = await db.equipment.findMany({ where: { name: { contains: "ZZ2" } }, select: { id:true,name:true,type:true,tempMin:true,tempMax:true,areaId:true } });
  console.log("DB-EQ", JSON.stringify(eq, null, 1));
  console.log("ERRORS", JSON.stringify(s.errors.slice(0,6)));
  await s.close();
})();
