// Проверка первой пачки правок: окна в оболочке, меню по ролям, напоминание заведующей.
import { openTelegramSession } from "./tg-session";
const OUT = process.env.SWEEP_OUT!; import fs from "node:fs"; fs.mkdirSync(OUT, { recursive: true });
(async () => {
  { const s = await openTelegramSession({ role: "managerA" }); await s.page.goto(s.base + "/settings/users", { waitUntil: "load", timeout: 300000 }); await s.page.waitForTimeout(3000);
    await s.page.getByRole("button", { name: /Пригласить по QR/ }).first().click(); await s.page.waitForTimeout(1500);
    console.log("окно QR:", JSON.stringify(await s.page.evaluate(`(function(){var d=Array.from(document.querySelectorAll('[role=dialog], .fixed.inset-0')).filter(function(e){return e.getBoundingClientRect().height>100}).pop();if(!d)return null;var r=d.getBoundingClientRect();var btn=Array.from(d.querySelectorAll('button')).filter(function(b){return /Сгенерировать|QR/.test(b.innerText)}).pop();var br=btn?btn.getBoundingClientRect():null;return {top:Math.round(r.top),h:Math.round(r.height),vh:innerHeight,btnVisible:br?br.top>=0&&br.bottom<=innerHeight:null}})()`))); await s.page.screenshot({ path: OUT + "/qr.png" }); await s.close(); }
  for (const role of ["headA", "cookA", "ownerA"]) { const s = await openTelegramSession({ role }); await s.page.waitForTimeout(2500);
    console.log(role, "дом:", new URL(s.page.url()).pathname, "| меню:", JSON.stringify(await s.page.evaluate(`Array.from(document.querySelectorAll('.mini-nav-rail a, .mini-root nav a')).map(function(a){return a.innerText.trim()+(a.getAttribute('aria-current')?'*':'')}).filter(function(t,i,arr){return t&&arr.indexOf(t)===i}).slice(0,6)`)));
    await s.page.goto(s.base + "/mini/sections", { waitUntil: "load", timeout: 300000 }); await s.page.waitForTimeout(2500); console.log(role, "разделы:", await s.page.evaluate(`Array.from(document.querySelectorAll('main a[href]')).map(function(a){return a.getAttribute('href')}).filter(function(h){return h&&h.startsWith('/')}).length`));
    if (role === "headA") { await s.page.goto(s.base + "/control-board", { waitUntil: "load", timeout: 300000 }); await s.page.waitForTimeout(3000); const b = s.page.getByRole("button", { name: /Напомнить всем/ }).first(); if (await b.isVisible().catch(() => false)) { s.errors.length = 0; await b.click(); await s.page.waitForTimeout(2500); console.log("напомнить всем:", await s.page.evaluate(`Array.from(document.querySelectorAll('[data-sonner-toast]')).map(function(t){return t.innerText.replace(/\s+/g,' ')}).join(' | ')`), "| ошибки:", s.errors.filter((e) => /remind/.test(e)).join(";") || "нет"); } else console.log("кнопки «Напомнить всем» нет"); }
    await s.close(); }
})().catch((e) => { console.log("FATAL", String(e).slice(0, 300)); process.exit(1); });
