// «Telegram» на стенде: гигиенический журнал — вкладка «Сегодня», блок заполнения сотрудника. Снимки экрана как видит человек.
import crypto from "node:crypto"; import fs from "node:fs"; import path from "node:path"; import { chromium } from "playwright";
import { db } from "../journal-responsibles-org-2026-09/e2e/db";
const BASE = "http://localhost:3021"; const TOKEN = process.env.TG_FAKE_TOKEN!; const OUT = process.env.SWEEP_OUT!; fs.mkdirSync(OUT, { recursive: true });
const HERE = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")); const HOST = fs.readFileSync(path.join(HERE, "tg-host.js"), "utf8"); const PROBE = fs.readFileSync(path.join(HERE, "text-probe.js"), "utf8");
const state = JSON.parse(fs.readFileSync(path.join(HERE, "..", "journal-responsibles-org-2026-09", "e2e", "state.json"), "utf8")); const CODE = process.env.SWEEP_CODE ?? "hygiene";
function forge(id: number) { const p = new URLSearchParams(); p.set("auth_date", String(Math.floor(Date.now() / 1000) - 5)); p.set("user", JSON.stringify({ id, first_name: "Т" })); const dcs = [...p.entries()].map(([k, v]) => `${k}=${v}`).sort().join("\n"); const s = crypto.createHmac("sha256", "WebAppData").update(TOKEN).digest(); p.set("hash", crypto.createHmac("sha256", s).update(dcs).digest("hex")); return p.toString(); }
(async () => { await db.user.updateMany({ where: { telegramChatId: "990005" }, data: { telegramChatId: null } }); const me = await db.user.update({ where: { email: state.users.ownerA.email }, data: { telegramChatId: "990005", themePreference: "light" }, select: { organizationId: true } });
  const doc = await db.journalDocument.findFirst({ where: { organizationId: me.organizationId, status: "active", template: { code: CODE } }, orderBy: { createdAt: "desc" }, select: { id: true } });
  const b = await chromium.launch({ headless: true }); const ctx = await b.newContext({ viewport: { width: 360, height: 640 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 }); await ctx.addInitScript(HOST);
  await ctx.addInitScript(`try{localStorage.setItem("wesetup.last-seen-build-sha","zzz")}catch(e){};document.addEventListener('DOMContentLoaded',function(){var s=document.createElement('style');s.textContent='nextjs-portal{display:none!important}';document.head.appendChild(s)})`);
  const page = await ctx.newPage(); await page.goto(`${BASE}/mini#tgWebAppData=${encodeURIComponent(forge(990005))}&tgWebAppVersion=8.0&tgWebAppPlatform=ios`, { waitUntil: "load", timeout: 300000 }); await page.waitForURL((u: URL) => u.pathname !== "/mini", { timeout: 120000 }).catch(() => null);
  await page.goto(`${BASE}/journals/${CODE}/documents/${doc!.id}`, { waitUntil: "load", timeout: 300000 }); await page.waitForTimeout(3000); await page.screenshot({ path: path.join(OUT, "1-open.png") });
  await page.mouse.wheel(0, 330); await page.waitForTimeout(600); await page.screenshot({ path: path.join(OUT, "2-scrolled.png") });
  const fill = page.getByRole("button", { name: /Заполнить/ }).first(); if (await fill.isVisible().catch(() => false)) { await fill.click(); await page.waitForTimeout(1200); await page.screenshot({ path: path.join(OUT, "3-fill.png") }); console.log("fill probe", JSON.stringify(await page.evaluate(PROBE.replace('document.querySelector("main") || document.body', 'document.body'))).slice(0, 1500));
    await page.mouse.wheel(0, 300); await page.waitForTimeout(500); await page.screenshot({ path: path.join(OUT, "4-fill-scrolled.png") }); }
  await b.close(); await db.$disconnect(); })().catch((e) => { console.log("FATAL", String(e).slice(0, 300)); process.exit(1); });
