// «Telegram» на стенде: кнопка подсказок в шапке — открывает лист, лист поверх нижнего меню, действия работают.
import crypto from "node:crypto"; import fs from "node:fs"; import path from "node:path"; import { chromium } from "playwright";
import { db } from "../journal-responsibles-org-2026-09/e2e/db";
const BASE = "http://localhost:3021"; const TOKEN = process.env.TG_FAKE_TOKEN!; const OUT = process.env.SWEEP_OUT!; fs.mkdirSync(OUT, { recursive: true });
const HERE = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")); const HOST = fs.readFileSync(path.join(HERE, "tg-host.js"), "utf8");
const state = JSON.parse(fs.readFileSync(path.join(HERE, "..", "journal-responsibles-org-2026-09", "e2e", "state.json"), "utf8"));
function forge(id: number) { const p = new URLSearchParams(); p.set("auth_date", String(Math.floor(Date.now() / 1000) - 5)); p.set("user", JSON.stringify({ id, first_name: "Т" })); const dcs = [...p.entries()].map(([k, v]) => `${k}=${v}`).sort().join("\n"); const s = crypto.createHmac("sha256", "WebAppData").update(TOKEN).digest(); p.set("hash", crypto.createHmac("sha256", s).update(dcs).digest("hex")); return p.toString(); }
(async () => { await db.user.updateMany({ where: { telegramChatId: "990005" }, data: { telegramChatId: null } }); const me = await db.user.update({ where: { email: state.users.ownerA.email }, data: { telegramChatId: "990005", themePreference: "light" }, select: { organizationId: true } });
  const doc = await db.journalDocument.findFirst({ where: { organizationId: me.organizationId, status: "active", template: { code: "hygiene" } }, select: { id: true } });
  const b = await chromium.launch({ headless: true }); const ctx = await b.newContext({ viewport: { width: 360, height: 640 }, isMobile: true, hasTouch: true }); await ctx.addInitScript(HOST);
  await ctx.addInitScript(`try{localStorage.setItem("wesetup.mini.tour.seen",String(Date.now()));localStorage.setItem("wesetup.last-seen-build-sha","zzz")}catch(e){};(function(){var s=document.createElement('style');s.textContent='nextjs-portal{display:none!important}';document.documentElement.appendChild(s)})()`);
  const page = await ctx.newPage(); await page.goto(`${BASE}/mini#tgWebAppData=${encodeURIComponent(forge(990005))}&tgWebAppVersion=8.0&tgWebAppPlatform=ios`, { waitUntil: "load", timeout: 300000 }); await page.waitForFunction(`!/Загружаем кабинет/.test(document.body.innerText)`, null, { timeout: 120000 }).catch(() => null);
  for (const [name, url] of [["doc", `/mini/documents/${doc!.id}`], ["site", "/settings/users"], ["home", "/mini"]] as const) { await page.goto(BASE + url, { waitUntil: "load", timeout: 300000 }); await page.waitForTimeout(2500);
    const floating = await page.evaluate(`Array.from(document.querySelectorAll('body .fixed')).filter(function(e){var r=e.getBoundingClientRect();return r.width>30&&r.width<70&&r.height<70&&r.right>300&&r.top>300&&getComputedStyle(e).visibility!=='hidden'}).length`);
    const btn = page.locator("#mini-fab-slot button").first(); const has = await btn.isVisible().catch(() => false); let sheet: any = null;
    if (has) { await btn.click(); await page.waitForTimeout(900); sheet = await page.evaluate(`(function(){var d=document.querySelector('[role=dialog]');if(!d)return null;var r=d.getBoundingClientRect();var rows=Array.from(d.querySelectorAll('button')).map(function(b){return b.innerText.trim().replace(/\s+/g,' ').slice(0,40)});var last=d.querySelectorAll('button');var lb=last[last.length-1].getBoundingClientRect();var top=document.elementFromPoint(lb.left+lb.width/2,lb.top+lb.height/2);return {bottom:Math.round(r.bottom),vh:innerHeight,rows:rows,lastClickable:!!top&&d.contains(top)}})()`); await page.screenshot({ path: path.join(OUT, `help-${name}.png`) }); await page.keyboard.press("Escape"); }
    console.log(name, JSON.stringify({ headerButton: has, floatingLeft: floating, sheet })); }
  await b.close(); await db.$disconnect(); })().catch((e) => { console.log("FATAL", String(e).slice(0, 300)); process.exit(1); });
