(function () {
  var de = document.documentElement, vw = de.clientWidth, vh = window.innerHeight;
  function label(el) { return (el.tagName.toLowerCase() + "." + String(el.className && el.className.baseVal !== undefined ? el.className.baseVal : el.className).replace(/\s+/g, ".").slice(0, 60) + " «" + (el.innerText || el.getAttribute("aria-label") || el.getAttribute("placeholder") || "").trim().replace(/\s+/g, " ").slice(0, 30) + "»"); }
  function inScroller(el) { var p = el.parentElement; while (p && p !== document.body) { var o = getComputedStyle(p).overflowX; if (o === "auto" || o === "scroll") return true; p = p.parentElement; } return false; }
  function hiddenByClip(el) { var p = el.parentElement; while (p && p !== document.body) { var s = getComputedStyle(p); if (s.overflowX === "hidden" || s.overflowX === "clip") { var r = p.getBoundingClientRect(); if (r.right <= vw + 1 && r.left >= -1) return true; } p = p.parentElement; } return false; }
  var root = document.querySelector("main") || document.body;
  var all = Array.from(root.querySelectorAll("*")).filter(function (e) { return e.offsetParent !== null || getComputedStyle(e).position === "fixed"; });
  // 1. Вылезает за экран по горизонтали и не лежит в прокручиваемом блоке.
  var clipped = [];
  all.forEach(function (el) { var r = el.getBoundingClientRect(); if (r.width < 2 || r.height < 2) return; if ((r.right > vw + 2 || r.left < -2) && !inScroller(el)) { var s = getComputedStyle(el); var deco = s.pointerEvents === "none" || el.getAttribute("aria-hidden") === "true" || /blur|absolute/.test(String(el.className)) && !el.innerText; if (deco) return; var txt = (el.innerText || "").trim(); if (!txt && !/^(input|button|select|textarea|img|svg)$/i.test(el.tagName)) return; if (clipped.length < 8 && !clipped.some(function (c) { return c.indexOf(label(el).slice(0, 25)) === 0; })) clipped.push(label(el) + " [" + Math.round(r.left) + ".." + Math.round(r.right) + "]" + (hiddenByClip(el) ? " обрезано" : "")); } });
  // 2. Текст не помещается в свой блок (обрезан без многоточия).
  var overflowText = [];
  all.forEach(function (el) { if (el.children.length > 0 && !/^(button|a|label|span|p|h1|h2|h3|td|th)$/i.test(el.tagName)) return; var s = getComputedStyle(el); if (!el.innerText || !el.innerText.trim()) return; if (el.scrollWidth > el.clientWidth + 3 && (s.overflowX === "hidden" || s.overflowX === "clip") && s.textOverflow !== "ellipsis" && s.whiteSpace === "nowrap" && el.clientWidth > 20) { if (overflowText.length < 8) overflowText.push(label(el) + " " + el.clientWidth + "<" + el.scrollWidth); } });
  // 3. Мелкие цели для пальца (< 32px по меньшей стороне), только видимые в первом экране и ниже.
  var tiny = [];
  Array.from(root.querySelectorAll("button, a[href], [role=button], input[type=checkbox], input[type=radio], select")).forEach(function (el) { if (el.offsetParent === null || el.disabled) return; var r = el.getBoundingClientRect(); if (r.width < 2) return; var lab = el.closest("label"); if (lab) { var lr = lab.getBoundingClientRect(); if (Math.min(lr.width, lr.height) >= 32) return; } if (el.tagName === "A" && getComputedStyle(el).display === "inline") return; if (Math.min(r.width, r.height) < 28 && tiny.length < 8) tiny.push(label(el) + " " + Math.round(r.width) + "x" + Math.round(r.height)); });
  // 4. Закреплённые элементы перекрывают кнопки и поля в первом экране.
  var overlap = [];
  var fixed = Array.from(document.querySelectorAll("body *")).filter(function (e) { var s = getComputedStyle(e); if (s.position !== "fixed" || s.visibility === "hidden" || s.pointerEvents === "none") return false; var r = e.getBoundingClientRect(); return r.width > 20 && r.height > 20 && r.width < vw * 0.6 && r.height < 120 && r.top < vh && r.bottom > 0 && !e.closest("nav") && !e.closest("header"); });
  Array.from(root.querySelectorAll("button, a[href], input, select, textarea")).forEach(function (el) { if (el.offsetParent === null) return; var r = el.getBoundingClientRect(); if (r.width < 2 || r.bottom < 0 || r.top > vh) return; fixed.forEach(function (f) { if (f.contains(el) || el.contains(f)) return; var fr = f.getBoundingClientRect(); var ix = Math.min(r.right, fr.right) - Math.max(r.left, fr.left), iy = Math.min(r.bottom, fr.bottom) - Math.max(r.top, fr.top); if (ix > 8 && iy > 8 && (ix * iy) / (r.width * r.height) > 0.3 && overlap.length < 6) overlap.push(label(el) + " под " + label(f).slice(0, 40)); }); });
  return { vw: vw, pageOverflow: de.scrollWidth > vw + 2 ? de.scrollWidth : 0, clipped: clipped, overflowText: overflowText, tiny: tiny, overlap: overlap, h1: (root.querySelector("h1") || {}).innerText || null };
})()
