import { openTelegramSession, db } from "../tg-session";
import { shot, go, probe } from "./lib";
const SUBMIT = `(()=>{const b=[...document.querySelectorAll('button')].filter(x=>x.innerText.trim()==='Завершить'||x.innerText.trim()==='Завершить осмотр');return b.length?{n:b.length,disabled:b[b.length-1].disabled}:null})()`;
const CLICK_SUBMIT = `(()=>{const b=[...document.querySelectorAll('button')].filter(x=>x.innerText.trim()==='Завершить');b[b.length-1].click();return b[b.length-1].disabled})()`;
(async () => {
const s = await openTelegramSession({ role: "cookA", width: 360, height: 640 });
const p = s.page;
const my: any = await p.evaluate(`fetch('/api/journal-task-claims/my',{cache:'no-store'}).then(r=>r.json())`);
const claimId = my?.claim?.id;
console.log("claim", claimId, my?.claim?.journalCode, my?.claim?.scopeLabel);
await go(p, s.base + "/mini/claim/" + claimId, 3000);
await p.waitForFunction(`/Возьми термометр/.test(document.body.innerText)`, { timeout: 120000 }).catch(()=>console.log("NO PIPELINE"));
await p.waitForTimeout(1200);
console.log("submit btn initial", JSON.stringify(await p.evaluate(SUBMIT)));
// отметить все 4 шага (кнопки-шаги — с aria-pressed)
const n = await p.evaluate(`(()=>{const b=[...document.querySelectorAll('button[aria-pressed]')];b.forEach(x=>x.click());return b.length})()`);
console.log("steps toggled", n);
await p.waitForTimeout(600);
console.log("after steps", JSON.stringify(await p.evaluate(SUBMIT)), "| blockers:", await p.evaluate(`(()=>{const d=[...document.querySelectorAll('div')].filter(x=>/Заполните:|Отметьте шаги/.test(x.innerText)&&x.children.length===0);return d.map(x=>x.innerText)})()`));
await p.fill('input[placeholder="напр. 4"]', "9");
await p.waitForTimeout(500);
console.log("after temp9", JSON.stringify(await p.evaluate(SUBMIT)));
await shot(p, "05-ready-vp");
await p.evaluate(CLICK_SUBMIT);
await p.waitForTimeout(3500);
console.log("BODY after submit(no corrective):\n" + (await probe(p)).bodyText.slice(0, 2500));
await shot(p, "05-err9", true);
await p.fill('input[placeholder="коротко описать"]', "Переставил продукты, вызвал мастера");
await p.waitForTimeout(400);
await p.evaluate(CLICK_SUBMIT);
await p.waitForTimeout(2500);
await shot(p, "05-warn", true);
console.log("BODY after submit2:\n" + (await probe(p)).bodyText.slice(0,2000));
await p.waitForTimeout(2500);
console.log("URL now", p.url());
const row = await db.journalTaskClaim.findUnique({ where: { id: claimId } });
console.log("DB CLAIM", JSON.stringify({status:row?.status, vs:(row as any)?.verificationStatus, cd: row?.completionData}, null, 1));
const capa = await db.capaTicket.findMany({ where: { organizationId: "e2e-org-a" }, orderBy:{createdAt:"desc"}, take: 2, select:{title:true,priority:true,category:true,sourceType:true}});
console.log("CAPA", JSON.stringify(capa));
console.log("ERRORS", JSON.stringify(s.errors));
await s.close();
})().catch((e) => { console.log("FATAL", String(e).slice(0, 2000)); process.exit(1); });
